<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHcqxdcx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHcqxdcx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHcqxdcx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHcqxdcx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerHcqxdcx\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Hcqxdcx',
    'container.build_id' => 'f517946e',
    'container.build_time' => 1523462029,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHcqxdcx');
